import { appShell } from "../../app/appShell.js";
import { icon } from "../../components/icons.js";
import { verificationServices } from "../../data/demoData.js";
import {canContinue,completeVerification,createVerificationState,nextVerificationStep,previousVerificationStep,selectService,updateVerificationFields} from "../../domain/verification.js";
import { escapeHtml, on } from "../../lib/html.js";
import { MockVerificationGateway } from "../../services/verificationGateway.js";
let state=createVerificationState();const gateway=new MockVerificationGateway();const stepOrder=["service","details","review","result"];const stepLabels=["انتخاب روایت","داده ورودی","مرور زمینه","ثبت رد"];
function stepper(){const active=stepOrder.indexOf(state.step);return `<div class="request-stepper">${stepLabels.map((l,i)=>`<div class="request-step" data-active="${i<=active}"><span class="request-step__number">${i+1}</span><span>${l}</span></div>`).join("")}</div>`;}
function serviceStep(){return `<div class="request-intro"><p class="eyebrow">NEW TRACE</p><h1>این درخواست قرار است چه داستانی را روشن کند؟</h1><p>نوع بررسی را انتخاب کنید. همه گزینه‌ها نمایشی‌اند و داده‌ای ارسال نمی‌شود.</p></div><div class="service-options">${verificationServices.map(s=>`<button class="service-option" type="button" data-service-id="${s.id}" aria-pressed="${state.payload.serviceId===s.id}"><span class="service-option__icon">${icon(s.icon,{size:23})}</span><strong>${s.title}</strong><small>${s.description}</small><span class="option-arrow">${icon("arrow")}</span></button>`).join("")}</div>`;}
function detailsStep(){return `<div class="request-intro"><p class="eyebrow">INPUT</p><h1>ورودی را با حداقل داده تعریف کنید.</h1><p>این فرم فقط اعتبارسنجی محلی دارد.</p></div><form id="verification-form" class="request-form"><div class="field"><label for="national-id">کد ملی نمونه</label><input id="national-id" name="nationalId" inputmode="numeric" maxlength="10" value="${escapeHtml(state.payload.nationalId)}" placeholder="۱۰ رقم"/><small>در نسخه واقعی، هدف و رضایت کنار این فیلد ثبت می‌شود.</small></div><div class="field"><label for="mobile">شماره موبایل نمونه</label><input id="mobile" name="mobile" inputmode="tel" maxlength="11" value="${escapeHtml(state.payload.mobile)}" placeholder="09xxxxxxxxx"/></div></form>`;}
function reviewStep(){const service=verificationServices.find(x=>x.id===state.payload.serviceId);return `<div class="request-intro"><p class="eyebrow">CONTEXT REVIEW</p><h1>پیش از ارسال، زمینه را دوباره بخوانید.</h1></div><div class="review-ledger"><div><small>نوع بررسی</small><strong>${escapeHtml(service?.title??"—")}</strong></div><div><small>شناسه نمونه</small><strong class="en">${escapeHtml(state.payload.nationalId)}</strong></div><div><small>موبایل نمونه</small><strong class="en">${escapeHtml(state.payload.mobile)}</strong></div><div><small>حالت اجرا</small><strong>Demo / بدون ذخیره</strong></div></div><div class="request-note">${icon("shield")} اتصال واقعی فقط پس از عبور از دروازه حقوقی و فنی فعال می‌شود.</div>`;}
function resultStep(){return `<div class="success-state"><div class="success-state__icon">${icon("check",{size:32})}</div><p class="eyebrow">TRACE CREATED</p><h1>رد نمایشی درخواست ساخته شد.</h1><p>شناسه پیگیری <strong class="en">${escapeHtml(state.referenceId??"—")}</strong></p><div class="result-timeline"><span>ورودی ثبت شد</span><span>زمینه مرور شد</span><span>درخواست پذیرفته شد</span></div><button id="restart-request" class="button button--secondary" type="button">شروع روایت جدید</button></div>`;}
function body(){if(state.step==="service")return serviceStep();if(state.step==="details")return detailsStep();if(state.step==="review")return reviewStep();return resultStep();}
function actions(){if(state.step==="result")return"";const first=state.step==="service",review=state.step==="review";return `<div class="request-actions">${first?"":'<button id="previous-step" class="button button--ghost" type="button">مرحله قبل</button>'}<button id="next-step" class="button button--primary" type="button" ${canContinue(state)?"":"disabled"}>${review?"ساخت رد نمایشی":"ادامه"} ${icon("arrow")}</button></div>`;}
export function renderRequestPage(){return appShell({content:`<section class="request-page"><div class="request-context"><span>${icon("story",{size:26})}</span><div><strong>Story trace builder</strong><small>از سؤال تا رد قابل بازگشت</small></div></div>${stepper()}<article class="request-card card">${body()}${actions()}</article></section>`,activePath:"/request",title:"جریان درخواست"});}
/** @param {() => void} rerender */
export function mountRequestPage(rerender){document.querySelectorAll("[data-service-id]").forEach(b=>on(b,"click",()=>{const id=b.getAttribute("data-service-id");if(id){state=selectService(state,id);rerender();}}));const form=document.querySelector("#verification-form");on(form,"input",e=>{if(!(e.target instanceof HTMLInputElement))return;state=updateVerificationFields(state,{[e.target.name]:e.target.value});const n=document.querySelector("#next-step");if(n instanceof HTMLButtonElement)n.disabled=!canContinue(state);});on(document.querySelector("#previous-step"),"click",()=>{state=previousVerificationStep(state);rerender();});on(document.querySelector("#next-step"),"click",async()=>{if(!canContinue(state))return;if(state.step!=="review"){state=nextVerificationStep(state);rerender();return;}const r=await gateway.submit({serviceId:state.payload.serviceId??"unknown",nationalId:state.payload.nationalId,mobile:state.payload.mobile});state=completeVerification(state,r.referenceId);rerender();});on(document.querySelector("#restart-request"),"click",()=>{state=createVerificationState();rerender();});}
